// CODEMAP.md at the repo root: every source file and what it's for, from its own first comment (JS) or docstring
// (Python), so a session finds the right file in one read instead of grepping. `node scripts/codemap.mjs` writes it;
// test/codemap.test.js fails when it's out of date. A file without a header comment is listed as such: add one.
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..', '..');
const GROUPS = [
  ['Desktop app: main process', 'desktop', /^(main\.js|preload\.cjs|start\.js)$/],
  ['Desktop app: main-process modules', 'desktop/lib', /\.js$/],
  ['Desktop window: pages', 'desktop/renderer/pages', /\.js$/],
  ['Desktop window: shared modules', 'desktop/renderer', /\.js$/],
  ['Desktop scripts', 'desktop/scripts', /\.(mjs|cjs|js)$/],
  ['Chrome extension', 'extension', /\.js$/],
  ['Python pipeline', 'src', /\.py$/, true],
  ['Telegram bot (worker)', 'worker/src', /\.js$/],
  ['Tools', 'tools', /\.(py|sh|mjs)$/],
];

function purpose(file) {
  const text = fs.readFileSync(file, 'utf8');
  const lines = text.split('\n');
  if (file.endsWith('.py')) {
    const doc = text.match(/^(?:#![^\n]*\n)?(?:#[^\n]*\n)*\s*(?:"""|''')\s*([^\n]*)/);
    if (doc?.[1]?.trim()) return doc[1].trim();
  }
  const comment = lines.find(line => /^\s*(\/\/|#(?!!))/.test(line) && !/eslint|@ts-|noqa|coding[:=]/.test(line));
  const first = lines.findIndex(line => line.trim() && !/^#!/.test(line) && !/^['"]use strict/.test(line));
  if (comment && lines.indexOf(comment) <= Math.max(first, 0) + 1) return comment.replace(/^\s*(\/\/|#)\s*/, '').trim();
  return '(no header comment: add one)';
}

function walk(dir, pattern, deep) {
  const full = path.join(root, dir);
  if (!fs.existsSync(full)) return [];
  return fs.readdirSync(full, {withFileTypes: true}).sort((a, b) => a.name.localeCompare(b.name)).flatMap(entry => {
    const rel = `${dir}/${entry.name}`;
    if (entry.isDirectory()) return deep && !/^(__pycache__|node_modules)$/.test(entry.name) ? walk(rel, pattern, deep) : [];
    return pattern.test(entry.name) && entry.name !== '__init__.py' ? [rel] : [];
  });
}

export function codemap() {
  const out = ['# Code map', '',
    'Generated by `node desktop/scripts/codemap.mjs` from each file\'s first comment or docstring; `desktop/test/codemap.test.js`',
    'fails when it is stale. Read this first to find the file; then read only that file. Rules and workflow: CLAUDE.md,',
    'skill `desktop-change` (the edit → check → push loop and known traps), skill `ui-look-and-feel` (screens).', ''];
  for (const [title, dir, pattern, deep] of GROUPS) {
    const found = walk(dir, pattern, deep);
    if (!found.length) continue;
    out.push(`## ${title}`, '');
    for (const file of found) out.push(`- \`${file}\` — ${purpose(path.join(root, file)).slice(0, 200)}`);
    out.push('');
  }
  return out.join('\n');
}

if (process.argv[1] === import.meta.filename) {
  fs.writeFileSync(path.join(root, 'CODEMAP.md'), codemap());
  console.log('CODEMAP.md written');
}
