// The pool of facts and advice rotated in the ticker on the Application sessions page (tips.js).
// evidence: 'research' = what published sources agree on (a fact, shown as "Fact"); 'advice' = common, sensible guidance
// (shown as "Tip"); 'to-test' = plausible, not verified: we test it against our own outcome data before calling it a fact.
// Honesty rule: no invented numbers, nothing that tells users to deceive an employer. Keep each text under 150 characters.
// evidence: 'recruiters' = what recruiters report in a few Reddit threads (shown as "Recruiters say"): firsthand, but not a survey (docs/research/ats-reddit-2026-10.md).
// ats: shown only while the session is on that application system (see atsOf in tips.js).
const HUNTR = 'https://huntr.co/blog/how-applicant-tracking-systems-work';
const TRUFFLE = 'https://www.hiretruffle.com/blog/knockout-questions';
const JOBSCAN = 'https://www.jobscan.co/blog/blog-ai-resume-screening/';
const HIRATION = 'https://www.hiration.com/blog/white-text-resume-hack/';
const BUILTIN = 'https://builtin.com/articles/hidden-ai-prompts-in-resume';

export const TIPS = [
  {id: 'no-auto-reject', evidence: 'research', category: 'ats', source: HUNTR,
    text: 'No major ATS rejects a CV on its own. The real risk is being ranked low and never opened.'},
  {id: 'knockout', evidence: 'research', category: 'knockout', source: TRUFFLE,
    text: 'The one real auto-reject is a knockout question (work permit, sponsorship, office days, a required licence), if the employer set one.'},
  {id: 'ai-ranking', evidence: 'research', category: 'ats', source: JOBSCAN,
    text: 'Some systems (Greenhouse, Workday) sort or grade applicants by match, so recruiters see the best matches first.'},
  {id: 'greenhouse-ranking', evidence: 'research', category: 'ats', ats: 'greenhouse', source: JOBSCAN,
    text: 'Greenhouse sorts applicants by how they match the role\'s criteria, but never advances or rejects anyone for the recruiter.'},
  {id: 'workday-grades', evidence: 'research', category: 'ats', ats: 'workday', source: JOBSCAN,
    text: 'Workday grades applicants A to D by how well their skills match the role. Keep a clear skills section.'},
  {id: 'ashby-human', evidence: 'advice', category: 'ats', ats: 'ashby',
    text: 'Ashby employers can auto-archive applications from your answers to their application questions. Answer them truthfully.'},
  {id: 'no-stuffing', evidence: 'advice', category: 'cv',
    text: 'Name a skill where you used it. A list of keywords reads thin to a recruiter, and nobody has shown a stuffing penalty.'},
  {id: 'no-white-text', evidence: 'research', category: 'cv', source: BUILTIN,
    text: 'Hidden white text is read by parsers and can get you flagged or blacklisted. It is never worth it.'},
  {id: 'posting-words', evidence: 'advice', category: 'cv',
    text: 'Use the posting\'s own words for skills you really have: "Kubernetes", not "k8s".'},
  {id: 'one-column', evidence: 'advice', category: 'cv',
    text: 'One column and standard headings (Experience, Education, Skills) are what parsers read best.'},
  {id: 'no-tables', evidence: 'to-test', category: 'cv',
    text: 'Some parsers may lose tables, text boxes or details in the page header. Not confirmed by recruiters: the plain-text paste shows it.'},
  {id: 'plain-text-check', evidence: 'advice', category: 'cv',
    text: 'Paste your CV into a plain text editor. If the order is scrambled there, a parser will struggle too.'},
  {id: 'skill-with-result', evidence: 'advice', category: 'cv',
    text: 'A skill next to a real result counts for more than the same word in a list.'},
  {id: 'quantify', evidence: 'advice', category: 'cv',
    text: '"Cut deploy time from 40 to 8 minutes" says more than "improved deployments".'},
  {id: 'tailor', evidence: 'advice', category: 'tailor',
    text: 'One tailored application to a good match beats five generic ones. Fewer, better.'},
  {id: 'cover-letter', evidence: 'advice', category: 'tailor',
    text: 'A short, specific cover letter (why this company, why you) beats a long generic one.'},
  {id: 'honest-skills', evidence: 'advice', category: 'tailor',
    text: 'Never claim a skill you don\'t have. The interview checks it, and the CV is what you are held to.'},
  {id: 'work-permit', evidence: 'advice', category: 'knockout',
    text: 'State your work permit or right to work clearly, wherever you apply. It is a common knockout question.'},
  {id: 'location-notice', evidence: 'advice', category: 'knockout',
    text: 'Answer location, office days and notice period honestly. Your CV and your answers should agree, or a recruiter will notice.'},
  {id: 'read-answers', evidence: 'advice', category: 'knockout',
    text: 'Job Pilotto fills the form and you click Submit. Read the answers once: knockout questions decide fast.'},
  {id: 'early', evidence: 'to-test', category: 'timing',
    text: 'Early applications are often seen first. Apply soon after a role is posted.'},
  {id: 'own-page', evidence: 'to-test', category: 'timing',
    text: 'The employer\'s own career page is usually a better route than an aggregator\'s link.'},
  {id: 'referral', evidence: 'recruiters', category: 'timing',
    text: 'A referral gets your CV read, not hired. It counts most from someone who knows your work, less as a casual forward.'},
  {id: 'wait-for-reply', evidence: 'advice', category: 'follow-up',
    text: 'Replies often take a week or more. Silence in the first days is not a rejection.'},
  {id: 'follow-up', evidence: 'advice', category: 'follow-up',
    text: 'No reply after 7 to 10 days? One short, polite follow-up is normal. More than one rarely helps.'},
  {id: 'keep-posting', evidence: 'advice', category: 'follow-up',
    text: 'Save the job posting when you apply. It often disappears before the interview.'},
  {id: 'track-patterns', evidence: 'advice', category: 'mindset',
    text: 'Track every application. Which boards and roles reply tells you where to spend your time.'},
  {id: 'apply-once', evidence: 'advice', category: 'mindset',
    text: 'The same job often sits on several boards. Apply once, through the best route, and keep the record.'},
  // From recruiters on Reddit (r/recruiting and others, Oct 2025 to Oct 2026): a handful of threads each, firsthand, not a survey.
  {id: 'rec-first-look', evidence: 'recruiters', category: 'ats',
    text: 'A recruiter reports 10 to 20 seconds per CV on a first pass: place, minimum experience, then skills.'},
  {id: 'rec-search', evidence: 'recruiters', category: 'ats',
    text: 'Recruiters search the pool with the posting\'s required words. State your key skills and title plainly, not by hint.'},
  {id: 'rec-boolean', evidence: 'recruiters', category: 'ats',
    text: 'One recruiter cuts 5,000 applicants to 40 with a Boolean search. A skill you never wrote down cannot be found.'},
  {id: 'rec-summary', evidence: 'recruiters', category: 'cv',
    text: 'A former recruiter skips a generic summary in half a second. Open with your title and something you did.'},
  {id: 'rec-grades', evidence: 'recruiters', category: 'ats',
    text: 'An AI grade is a sort order: one recruiter says they have hired people it graded D, and overrides it by hand.'},
  {id: 'rec-fast-no', evidence: 'recruiters', category: 'follow-up',
    text: 'A rejection within hours is not proof of an AI decision: one recruiter\'s system sends rejection emails in a night batch.'},
  {id: 'rec-ai-polish', evidence: 'recruiters', category: 'cv',
    text: 'A hiring manager is fine with an AI-polished CV if it is true. What they test is whether you can back it up live.'},
  {id: 'rec-yes-no', evidence: 'recruiters', category: 'knockout',
    text: '"Do you require sponsorship?" and "Can you be in the office three days a week?" are typical yes/no filters.'},
  {id: 'rec-reject-or-flag', evidence: 'recruiters', category: 'knockout',
    text: 'For some employers a wrong answer rejects you; for others it only flags you for review. You cannot tell which.'},
  {id: 'photo-optional', evidence: 'advice', category: 'cv',
    text: 'A photo is optional in Switzerland and usually left out in the US and UK. Keep a version without one.'},
  {id: 'agree-with-cv', evidence: 'advice', category: 'knockout',
    text: 'Keep residence, relocation, office days and work permit the same on the CV and in the form. A contradiction costs trust.'},
  // Interviews and what comes after them (the Learn stop). Advice, no numbers: they are about how to use what the app already keeps.
  {id: 'iv-review-soon', evidence: 'advice', category: 'interview',
    text: 'Review an interview within a day. What you still remember of the questions is the most useful part.'},
  {id: 'iv-weak-topic', evidence: 'advice', category: 'interview',
    text: 'Pick one weak topic from your last review and practise it before the next round.'},
  {id: 'iv-example', evidence: 'advice', category: 'interview',
    text: 'Answer with the situation, what you did and the result. One real example beats three general claims.'},
  {id: 'iv-ask-them', evidence: 'advice', category: 'interview',
    text: 'Prepare two questions about the team and how success is measured. You are choosing them too.'},
  {id: 'iv-consent', evidence: 'advice', category: 'interview',
    text: 'Ask everyone before you record, every time. Many places require everyone\'s consent.'},
  {id: 'rejection-data', evidence: 'advice', category: 'mindset',
    text: 'A rejection with no reason is still data. Note the stage and date: patterns show after a handful.'},
];
