// One Apply conversation in its '💬 Conversation' toggle, the shared sample of both sides (tests/fixtures/stores/conversation.json,
// generated by lib/transcript.js in TZ=UTC; src/stores/notion_conversation.py matches it too): a format change on either side fails.
process.env.TZ = 'UTC';   // the sample's times ("You · 21:42") are UTC; set before any Date is made
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {test} from 'node:test';
import {HEADING, blocks, load} from '../lib/transcript.js';

const sample = JSON.parse(fs.readFileSync(new URL('../../tests/fixtures/stores/conversation.json', import.meta.url), 'utf8'));

test('the conversation becomes exactly the sample\'s blocks', () => {
  assert.deepEqual(blocks(sample.talk), sample.blocks);
});

test('reading the sample\'s blocks back, as Notion returns them, gives the sample\'s conversation', async () => {
  // As Notion returns blocks: each with an id, and every text part with its plain_text.
  const asRead = (block, n) => {
    const body = block[block.type];
    return {id: `b${n}`, type: block.type, [block.type]: {...body, rich_text: (body.rich_text || []).map(part => ({...part, plain_text: part.text.content}))}};
  };
  const toggle = {id: 'conversation', type: 'toggle', toggle: {rich_text: [{type: 'text', text: {content: `${HEADING} · 5 messages and steps`},
    plain_text: `${HEADING} · 5 messages and steps`}]}};
  const pages = {'blocks/row/children': [toggle], 'blocks/conversation/children': sample.blocks.map(asRead)};
  const call = async (method, route) => ({results: pages[route.split('?')[0]] || [], has_more: false});
  assert.deepEqual(await load(call, 'row'), sample.loaded);
});
