#!/usr/bin/env python3
"""The Job Pilotto Notion workspace as code: config/notion_schema.json.

One file lists every database (title, icon, every column with its type, options, relations, rollups and
formulas) and every page the code uses. From it:
  - tools/notion_template.py builds the public template (no live workspace needed);
  - the desktop app creates what a user's workspace is missing and adds missing columns (desktop/lib/schema.js),
    on connect and at start-up, so a workspace can always be rebuilt from scratch;
  - tests check that every column the code needs is in it.

    NOTION_TOKEN=... python3 tools/notion_schema.py snapshot   # owner's live databases -> config/notion_schema.json
    python3 tools/notion_schema.py check                       # the file covers every required column

Run `snapshot` after changing a database in Notion (a column, an option), then commit the file.
Views aren't in Notion's public API, so they aren't in the schema.
"""
import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'tools'))
from notion_template import DATABASES, PAGES, request  # noqa: E402

SCHEMA = ROOT / 'config' / 'notion_schema.json'
TEMPLATE = ROOT / 'config' / 'notion_template.json'
# Pages the app creates itself next to the Profile (their code writes the content).
APP_PAGES = {
    'NOTION_SEARCH_SETTINGS_PAGE': ('⚙️', 'Search settings', 'src/notion/search_settings.py'),
    'NOTION_KNOWLEDGE_PAGE': ('🧠', 'Form knowledge', 'desktop/lib/knowledge.js'),
}


def column(prop, env_of):
    """A live property -> its schema entry (enough to create it again)."""
    kind = prop['type']
    entry = {'type': kind}
    body = prop.get(kind) or {}
    if kind in ('select', 'multi_select'):
        entry['options'] = [{'name': o['name'], 'color': o.get('color', 'default')} for o in body.get('options', [])]
    elif kind == 'status':
        entry['options'] = [o['name'] for o in body.get('options', [])]
    elif kind == 'number':
        entry['format'] = body.get('format', 'number')
    elif kind == 'relation':
        entry['database'] = env_of.get(body['database_id'].replace('-', ''), body['database_id'])
        if body.get('type') == 'dual_property':
            entry['synced_property'] = (body.get('dual_property') or {}).get('synced_property_name')
    elif kind == 'rollup':
        entry.update(relation=body['relation_property_name'], property=body['rollup_property_name'], function=body['function'])
    elif kind == 'formula':
        entry['expression'] = body['expression']
    return entry


def snapshot(token):
    env_of = {db: env for env, db in DATABASES.items()}
    databases = {}
    for env, db in DATABASES.items():
        src = request('GET', f'databases/{db}', token=token)
        databases[env] = {
            'title': ''.join(t['plain_text'] for t in src['title']),
            'icon': (src.get('icon') or {}).get('emoji'),
            'description': ''.join(t['plain_text'] for t in src.get('description') or []),
            'columns': {name: column(prop, env_of) for name, prop in sorted(src['properties'].items())},
        }
    pages = {env: {'emoji': emoji, 'title': title} for env, (emoji, title) in PAGES.items()}
    pages.update({env: {'emoji': emoji, 'title': title, 'made_by': source} for env, (emoji, title, source) in APP_PAGES.items()})
    return {'_comment': 'Generated by tools/notion_schema.py snapshot from the owner workspace. Do not edit by hand.',
            'databases': databases, 'pages': pages}


def load(path=SCHEMA):
    return json.loads(Path(path).read_text())


def api_property(entry, database_id=None):
    """A schema column -> a Notion API property definition (relations need their target's id)."""
    kind = entry['type']
    if kind in ('select', 'multi_select'):
        return {kind: {'options': entry.get('options', [])}}
    if kind == 'number':
        return {'number': {'format': entry.get('format', 'number')}}
    if kind == 'status':
        return {'status': {}}
    if kind == 'unique_id':
        return {'unique_id': {'prefix': None}}
    if kind == 'relation':
        return {'relation': {'database_id': database_id, **({'type': 'dual_property', 'dual_property': {}} if 'synced_property' in entry
                                                             else {'type': 'single_property', 'single_property': {}})}}
    if kind == 'rollup':
        return {'rollup': {'relation_property_name': entry['relation'], 'rollup_property_name': entry['property'],
                           'function': entry['function']}}
    if kind == 'formula':
        return {'formula': {'expression': entry['expression']}}
    return {kind: {}}


def problems(schema, template):
    """Required columns (config/notion_template.json) missing from the schema, and template titles that differ."""
    found = []
    for env, required in template['required_properties'].items():
        db = schema['databases'].get(env)
        if not db:
            found.append(f'{env}: no database in the schema')
            continue
        found += [f'{env}: column "{name}" missing' for name in required if name not in db['columns']]
        if db['title'] != template['databases'][env]:
            found.append(f'{env}: title "{db["title"]}" but the app looks for "{template["databases"][env]}"')
    found += [f'{env}: page missing' for env in template['pages'] if env not in schema['pages']]
    return found


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('command', choices=('snapshot', 'check'))
    args = parser.parse_args(argv)
    if args.command == 'snapshot':
        token = os.getenv('NOTION_TOKEN')
        if not token:
            parser.error('NOTION_TOKEN is required (the owner workspace integration)')
        schema = snapshot(token)
        SCHEMA.write_text(json.dumps(schema, indent=1, ensure_ascii=False) + '\n')
        print(f"Wrote {SCHEMA.relative_to(ROOT)}: {len(schema['databases'])} databases, "
              f"{sum(len(d['columns']) for d in schema['databases'].values())} columns, {len(schema['pages'])} pages.")
    found = problems(load(), json.loads(TEMPLATE.read_text()))
    for line in found:
        print(f'✗ {line}')
    if not found:
        print('✓ The schema covers every database, column and page the code needs.')
    return 1 if found else 0


if __name__ == '__main__':
    raise SystemExit(main())
